"""add expiration date and reminder flags to documents

Revision ID: 41197e1c49d6
Revises: fe1d049c965b
Create Date: 2025-03-30 15:41:09.665534

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '41197e1c49d6'
down_revision: Union[str, None] = 'fe1d049c965b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('gcs_file_path', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('gcs_uploaded', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('documents', sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('telegram_reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('sms_reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('call_reminder_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'gcs_uploaded')
    op.drop_column('documents', 'gcs_file_path')
    op.drop_column('documents', 'call_reminder_sent')
    op.drop_column('documents', 'sms_reminder_sent')
    op.drop_column('documents', 'telegram_reminder_sent')
    op.drop_column('documents', 'expiration_date')
    # ### end Alembic commands ###
